/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AeMorphComponent {
    'aesize': string;
    'aetype': string;
    'arialabel': string;
    'color': string;
    'name': string;
  }
}

declare global {


  interface HTMLAeMorphComponentElement extends Components.AeMorphComponent, HTMLStencilElement {}
  var HTMLAeMorphComponentElement: {
    prototype: HTMLAeMorphComponentElement;
    new (): HTMLAeMorphComponentElement;
  };
  interface HTMLElementTagNameMap {
    'ae-morph-component': HTMLAeMorphComponentElement;
  }
}

declare namespace LocalJSX {
  interface AeMorphComponent extends JSXBase.HTMLAttributes<HTMLAeMorphComponentElement> {
    'aesize'?: string;
    'aetype'?: string;
    'arialabel'?: string;
    'color'?: string;
    'name'?: string;
  }

  interface IntrinsicElements {
    'ae-morph-component': AeMorphComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


